### ISSUE TITLE
Align on a definition of success for 18F

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/dotgov#20]
- [x] Discuss various goals and synthesize
- [x] Document goals and tradeoffs
- [x] Prioritize and commit to goals
- [x] Prioritize and commit to milestones, short-term and long-term priorities, and user groups
- [x] Document in product strategy in github repo

**Comment by colinmurphy01** [comment]
Most of this was conducted in this doc: https://docs.google.com/document/d/14Vlz1wkRpPu_-4BFFMRsqHu0JHS0OedmhLhScs9RnVc/edit#
